server:
  port: 8080

spring:
  application:
    name: gp-api-core

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
    br.com.greenpark.estacionamento.core: INFO
