server:
  port: 8081

spring:
  application:
    name: gp-bff

gp:
  core:
    base-url: ${CORE_BASE_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
    br.com.greenpark.estacionamento.bff: INFO
